export type SkillProps = {
  group: string
  skills: {
    label: string
    value: string
  }[]
}

export const SKILLS: SkillProps[] = [
  {
    group: "Technical & Development Skills",
    skills: [
      { label: "Android Development", value: "android_development" },
      { label: "iOS Development", value: "ios_development" },
      { label: "Web Development", value: "web_development" },
      { label: "Front-End Development", value: "front_end_development" },
      { label: "Back-End Development", value: "back_end_development" },
      { label: "DevOps", value: "devops" },
      { label: "Blockchain Development", value: "blockchain_development" },
      { label: "Data Science", value: "data_science" },
      { label: "Big Data", value: "big_data" },
      { label: "Artificial Intelligence", value: "artificial_intelligence" },
      { label: "Deep Learning", value: "deep_learning" },
      { label: "Natural Language Processing (NLP)", value: "nlp" },
      { label: "Robotics", value: "robotics" },
      { label: "Game Development", value: "game_development" },
      { label: "Augmented Reality (AR)", value: "augmented_reality" },
      { label: "Virtual Reality (VR)", value: "virtual_reality" },
      { label: "UI Development", value: "ui_development" },
      { label: "API Development", value: "api_development" },
      { label: "Software Testing", value: "software_testing" },
      { label: "Mobile App Development", value: "mobile_app_development" },
    ],
  },
  {
    group: "Programming & Technical Skills",
    skills: [
      { label: "JavaScript", value: "javascript" },
      { label: "Python", value: "python" },
      { label: "HTML", value: "html" },
      { label: "CSS", value: "css" },
      { label: "React", value: "react" },
      { label: "Node.js", value: "nodejs" },
      { label: "TypeScript", value: "typescript" },
      { label: "Java", value: "java" },
      { label: "SQL", value: "sql" },
      { label: "Machine Learning", value: "machine_learning" },
      { label: "Cloud Computing", value: "cloud_computing" },
      { label: "Cybersecurity", value: "cybersecurity" },
      { label: "Full-Stack Development", value: "full_stack" },
    ],
  },
  {
    group: "Design & Creative Skills",
    skills: [
      { label: "Graphic Design", value: "graphic_design" },
      { label: "UI/UX Design", value: "ui_ux_design" },
      { label: "Video Editing", value: "video_editing" },
      { label: "Photography", value: "photography" },
      { label: "Illustration", value: "illustration" },
      { label: "Animation", value: "animation" },
      { label: "3D Modeling", value: "3d_modeling" },
      { label: "Interior Design", value: "interior_design" },
      { label: "Architectural Design", value: "architectural_design" },
      { label: "Fashion Design", value: "fashion_design" },
      { label: "Creative Writing", value: "creative_writing" },
      { label: "Copywriting", value: "copywriting" },
      { label: "Content Creation", value: "content_creation" },
      { label: "Branding", value: "branding" },
      { label: "Podcasting", value: "podcasting" },
      { label: "Vlogging", value: "vlogging" },
    ],
  },
  {
    group: "Business & Management Skills",
    skills: [
      { label: "Project Management", value: "project_management" },
      { label: "Marketing", value: "marketing" },
      { label: "Consulting", value: "consulting" },
      { label: "Sales", value: "sales" },
      { label: "Public Speaking", value: "public_speaking" },
      { label: "Entrepreneurship", value: "entrepreneurship" },
      { label: "Business Strategy", value: "business_strategy" },
      { label: "Pitching", value: "pitching" },
      { label: "Leadership", value: "leadership" },
      { label: "Negotiation", value: "negotiation" },
      { label: "SEO (Search Engine Optimization)", value: "seo" },
      { label: "Social Media Marketing", value: "social_media_marketing" },
      { label: "Digital Marketing", value: "digital_marketing" },
      { label: "Email Marketing", value: "email_marketing" },
      { label: "Affiliate Marketing", value: "affiliate_marketing" },
      { label: "Growth Hacking", value: "growth_hacking" },
      { label: "E-commerce", value: "e_commerce" },
      { label: "Market Research", value: "market_research" },
      { label: "Customer Service", value: "customer_service" },
      { label: "Human Resources", value: "human_resources" },
      { label: "Talent Acquisition", value: "talent_acquisition" },
      { label: "Financial Analysis", value: "financial_analysis" },
      { label: "Bookkeeping", value: "bookkeeping" },
      { label: "Supply Chain Management", value: "supply_chain_management" },
      { label: "Product Management", value: "product_management" },
      { label: "Scrum", value: "scrum" },
      { label: "Agile Methodology", value: "agile_methodology" },
    ],
  },
  {
    group: "Personal Development & Soft Skills",
    skills: [
      { label: "Communication", value: "communication" },
      { label: "Presentation", value: "presentation" },
      { label: "Time Management", value: "time_management" },
      { label: "Teamwork", value: "teamwork" },
      { label: "Problem Solving", value: "problem_solving" },
      { label: "Critical Thinking", value: "critical_thinking" },
      { label: "Conflict Resolution", value: "conflict_resolution" },
      { label: "Emotional Intelligence", value: "emotional_intelligence" },
      { label: "Storytelling", value: "storytelling" },
      { label: "Personal Finance", value: "personal_finance" },
      { label: "Photography Editing", value: "photography_editing" },
      { label: "Cooking Gourmet", value: "cooking_gourmet" },
      { label: "Bartending", value: "bartending" },
      { label: "Travel Planning", value: "travel_planning" },
      { label: "Public Relations", value: "public_relations" },
      { label: "Online Tutoring", value: "online_tutoring" },
    ],
  },
  {
    group: "Arts & Entertainment Skills",
    skills: [
      { label: "Singing", value: "singing" },
      { label: "Dancing", value: "dancing" },
      { label: "Acting", value: "acting" },
      { label: "Music Production", value: "music_production" },
      { label: "DJing", value: "djing" },
      { label: "Instrument Playing", value: "instrument_playing" },
    ],
  },
  {
    group: "Miscellaneous Skills",
    skills: [
      { label: "Cooking", value: "cooking" },
      { label: "Baking", value: "baking" },
      { label: "Carpentry", value: "carpentry" },
      { label: "Gardening", value: "gardening" },
      { label: "Yoga", value: "yoga" },
      { label: "Meditation", value: "meditation" },
      { label: "Fitness Training", value: "fitness_training" },
      { label: "Event Planning", value: "event_planning" },
    ],
  },
]
export type SkillOption = {
  label: string
  value: string
  group: string
}

export const SKILLS_Beta: SkillOption[] = [
  // --- Technical & Development Skills ---
  {
    label: "Android Development",
    value: "android-development",
    group: "Technical & Development",
  },
  {
    label: "iOS Development",
    value: "ios-development",
    group: "Technical & Development",
  },
  {
    label: "Web Development",
    value: "web-development",
    group: "Technical & Development",
  },
  {
    label: "Frontend Development",
    value: "frontend-development",
    group: "Technical & Development",
  },
  {
    label: "Backend Development",
    value: "backend-development",
    group: "Technical & Development",
  },
  {
    label: "Full Stack Development",
    value: "full-stack-development",
    group: "Technical & Development",
  },
  { label: "DevOps", value: "devops", group: "Technical & Development" },
  {
    label: "Cloud Computing (AWS, Azure, GCP)",
    value: "cloud-computing",
    group: "Technical & Development",
  },
  {
    label: "Database Management (SQL, NoSQL)",
    value: "database-management",
    group: "Technical & Development",
  },
  {
    label: "API Development (REST, GraphQL)",
    value: "api-development",
    group: "Technical & Development",
  },
  {
    label: "Microservices Architecture",
    value: "microservices-architecture",
    group: "Technical & Development",
  },
  {
    label: "Serverless Architecture",
    value: "serverless-architecture",
    group: "Technical & Development",
  },
  {
    label: "Containerization (Docker, Kubernetes)",
    value: "containerization",
    group: "Technical & Development",
  },
  {
    label: "Software Testing (Unit, Integration, E2E)",
    value: "software-testing",
    group: "Technical & Development",
  },
  {
    label: "Mobile App Development (React Native, Flutter)",
    value: "mobile-app-development",
    group: "Technical & Development",
  },
  {
    label: "Game Development",
    value: "game-development",
    group: "Technical & Development",
  },
  {
    label: "Cybersecurity",
    value: "cybersecurity",
    group: "Technical & Development",
  },
  {
    label: "Blockchain Development",
    value: "blockchain-development",
    group: "Technical & Development",
  },
  {
    label: "Internet of Things (IoT)",
    value: "internet-of-things",
    group: "Technical & Development",
  },
  {
    label: "Embedded Systems",
    value: "embedded-systems",
    group: "Technical & Development",
  },
  { label: "Robotics", value: "robotics", group: "Technical & Development" },
  {
    label: "AR/VR Development",
    value: "ar-vr-development",
    group: "Technical & Development",
  },
  {
    label: "UI Development",
    value: "ui-development",
    group: "Technical & Development",
  },
  {
    label: "UX Development",
    value: "ux-development",
    group: "Technical & Development",
  },
  {
    label: "Technical Writing",
    value: "technical-writing",
    group: "Technical & Development",
  },
  {
    label: "Version Control (Git)",
    value: "version-control",
    group: "Technical & Development",
  },
  {
    label: "Code Review",
    value: "code-review",
    group: "Technical & Development",
  },
  { label: "Debugging", value: "debugging", group: "Technical & Development" },
  {
    label: "Web3 Development",
    value: "web3-development",
    group: "Technical & Development",
  },

  // --- Programming Languages & Frameworks ---
  { label: "JavaScript", value: "javascript", group: "Programming" },
  { label: "TypeScript", value: "typescript", group: "Programming" },
  { label: "Python", value: "python", group: "Programming" },
  { label: "Java", value: "java", group: "Programming" },
  { label: "C#", value: "c-sharp", group: "Programming" },
  { label: "C++", value: "c-plus-plus", group: "Programming" },
  { label: "C", value: "c", group: "Programming" },
  { label: "Go", value: "go", group: "Programming" },
  { label: "Rust", value: "rust", group: "Programming" },
  { label: "Kotlin", value: "kotlin", group: "Programming" },
  { label: "Swift", value: "swift", group: "Programming" },
  { label: "PHP", value: "php", group: "Programming" },
  { label: "Ruby", value: "ruby", group: "Programming" },
  { label: "SQL", value: "sql", group: "Programming" },
  { label: "HTML", value: "html", group: "Programming" },
  { label: "CSS", value: "css", group: "Programming" },
  { label: "React", value: "react", group: "Programming" },
  { label: "Angular", value: "angular", group: "Programming" },
  { label: "Vue.js", value: "vue-js", group: "Programming" },
  { label: "Node.js", value: "node-js", group: "Programming" },
  { label: "Express.js", value: "express-js", group: "Programming" },
  { label: "Spring Boot", value: "spring-boot", group: "Programming" },
  { label: "Django", value: "django", group: "Programming" },
  { label: "Flask", value: "flask", group: "Programming" },
  { label: "Ruby on Rails", value: "ruby-on-rails", group: "Programming" },
  { label: ".NET", value: "dot-net", group: "Programming" },
  { label: "ASP.NET", value: "asp-net", group: "Programming" },
  { label: "Laravel", value: "laravel", group: "Programming" },
  { label: "Symfony", value: "symfony", group: "Programming" },
  { label: "CodeIgniter", value: "codeigniter", group: "Programming" },
  { label: "Zend Framework", value: "zend-framework", group: "Programming" },
  { label: "CakePHP", value: "cakephp", group: "Programming" },
  { label: "Yii", value: "yii", group: "Programming" },
  { label: "Next.js", value: "next-js", group: "Programming" },
  { label: "Nuxt.js", value: "nuxt-js", group: "Programming" },
  { label: "Gatsby", value: "gatsby", group: "Programming" },
  { label: "Svelte", value: "svelte", group: "Programming" },
  { label: "Ember.js", value: "ember-js", group: "Programming" },
  { label: "Backbone.js", value: "backbone-js", group: "Programming" },
  { label: "GraphQL", value: "graphql", group: "Programming" },
  { label: "TensorFlow", value: "tensorflow", group: "Programming" },
  { label: "PyTorch", value: "pytorch", group: "Programming" },
  { label: "Keras", value: "keras", group: "Programming" },
  { label: "Scikit-learn", value: "scikit-learn", group: "Programming" },
  { label: "Pandas", value: "pandas", group: "Programming" },
  { label: "NumPy", value: "numpy", group: "Programming" },
  { label: "Matplotlib", value: "matplotlib", group: "Programming" },
  { label: "Seaborn", value: "seaborn", group: "Programming" },
  { label: "OpenCV", value: "opencv", group: "Programming" },

  // --- Data Science & AI ---
  { label: "Data Science", value: "data-science", group: "Data Science & AI" },
  {
    label: "Machine Learning",
    value: "machine-learning",
    group: "Data Science & AI",
  },
  {
    label: "Deep Learning",
    value: "deep-learning",
    group: "Data Science & AI",
  },
  {
    label: "Artificial Intelligence (AI)",
    value: "artificial-intelligence",
    group: "Data Science & AI",
  },
  {
    label: "Natural Language Processing (NLP)",
    value: "natural-language-processing",
    group: "Data Science & AI",
  },
  {
    label: "Computer Vision",
    value: "computer-vision",
    group: "Data Science & AI",
  },
  {
    label: "Big Data Analytics",
    value: "big-data-analytics",
    group: "Data Science & AI",
  },
  {
    label: "Data Visualization",
    value: "data-visualization",
    group: "Data Science & AI",
  },
  { label: "Data Mining", value: "data-mining", group: "Data Science & AI" },
  {
    label: "Statistical Analysis",
    value: "statistical-analysis",
    group: "Data Science & AI",
  },
  {
    label: "Predictive Modeling",
    value: "predictive-modeling",
    group: "Data Science & AI",
  },
  {
    label: "Data Engineering",
    value: "data-engineering",
    group: "Data Science & AI",
  },
  {
    label: "Data Warehousing",
    value: "data-warehousing",
    group: "Data Science & AI",
  },
  {
    label: "Business Intelligence",
    value: "business-intelligence",
    group: "Data Science & AI",
  },

  // --- Design & Creative ---
  { label: "UI/UX Design", value: "ui-ux-design", group: "Design & Creative" },
  {
    label: "Graphic Design",
    value: "graphic-design",
    group: "Design & Creative",
  },
  { label: "Web Design", value: "web-design", group: "Design & Creative" },
  {
    label: "Interaction Design",
    value: "interaction-design",
    group: "Design & Creative",
  },
  {
    label: "Motion Graphics",
    value: "motion-graphics",
    group: "Design & Creative",
  },
  { label: "Illustration", value: "illustration", group: "Design & Creative" },
  { label: "3D Modeling", value: "3d-modeling", group: "Design & Creative" },
  { label: "Animation", value: "animation", group: "Design & Creative" },
  {
    label: "Video Editing",
    value: "video-editing",
    group: "Design & Creative",
  },
  { label: "Photography", value: "photography", group: "Design & Creative" },
  {
    label: "Visual Effects (VFX)",
    value: "visual-effects",
    group: "Design & Creative",
  },
  { label: "Game Design", value: "game-design", group: "Design & Creative" },
  { label: "Sound Design", value: "sound-design", group: "Design & Creative" },
  {
    label: "Music Production",
    value: "music-production",
    group: "Design & Creative",
  },
  {
    label: "Interior Design",
    value: "interior-design",
    group: "Design & Creative",
  },
  {
    label: "Fashion Design",
    value: "fashion-design",
    group: "Design & Creative",
  },
  {
    label: "Product Design",
    value: "product-design",
    group: "Design & Creative",
  },
  {
    label: "User Research",
    value: "user-research",
    group: "Design & Creative",
  },
  {
    label: "Usability Testing",
    value: "usability-testing",
    group: "Design & Creative",
  },
  { label: "Prototyping", value: "prototyping", group: "Design & Creative" },
  { label: "Wireframing", value: "wireframing", group: "Design & Creative" },
  {
    label: "Storyboarding",
    value: "storyboarding",
    group: "Design & Creative",
  },
  { label: "Color Theory", value: "color-theory", group: "Design & Creative" },
  { label: "Typography", value: "typography", group: "Design & Creative" },

  // --- Business & Management ---
  {
    label: "Project Management",
    value: "project-management",
    group: "Business & Management",
  },
  {
    label: "Agile Methodologies",
    value: "agile-methodologies",
    group: "Business & Management",
  },
  { label: "Scrum", value: "scrum", group: "Business & Management" },
  { label: "Kanban", value: "kanban", group: "Business & Management" },
  {
    label: "Product Management",
    value: "product-management",
    group: "Business & Management",
  },
  {
    label: "Business Analysis",
    value: "business-analysis",
    group: "Business & Management",
  },
  {
    label: "Risk Management",
    value: "risk-management",
    group: "Business & Management",
  },
  {
    label: "Change Management",
    value: "change-management",
    group: "Business & Management",
  },
  {
    label: "Strategic Planning",
    value: "strategic-planning",
    group: "Business & Management",
  },
  {
    label: "Business Development",
    value: "business-development",
    group: "Business & Management",
  },
  {
    label: "Entrepreneurship",
    value: "entrepreneurship",
    group: "Business & Management",
  },
  {
    label: "Startup Development",
    value: "startup-development",
    group: "Business & Management",
  },
  {
    label: "Venture Capital",
    value: "venture-capital",
    group: "Business & Management",
  },
  {
    label: "Angel Investing",
    value: "angel-investing",
    group: "Business & Management",
  },
  {
    label: "Financial Modeling",
    value: "financial-modeling",
    group: "Business & Management",
  },
  {
    label: "Financial Analysis",
    value: "financial-analysis",
    group: "Business & Management",
  },
  { label: "Accounting", value: "accounting", group: "Business & Management" },
  {
    label: "Bookkeeping",
    value: "bookkeeping",
    group: "Business & Management",
  },
  { label: "Auditing", value: "auditing", group: "Business & Management" },
  { label: "Taxation", value: "taxation", group: "Business & Management" },
  {
    label: "Human Resources (HR)",
    value: "human-resources",
    group: "Business & Management",
  },
  {
    label: "Recruitment",
    value: "recruitment",
    group: "Business & Management",
  },
  {
    label: "Talent Management",
    value: "talent-management",
    group: "Business & Management",
  },
  {
    label: "Training and Development",
    value: "training-and-development",
    group: "Business & Management",
  },
  {
    label: "Performance Management",
    value: "performance-management",
    group: "Business & Management",
  },
  {
    label: "Employee Relations",
    value: "employee-relations",
    group: "Business & Management",
  },
  {
    label: "Operations Management",
    value: "operations-management",
    group: "Business & Management",
  },
  {
    label: "Supply Chain Management",
    value: "supply-chain-management",
    group: "Business & Management",
  },
  { label: "Logistics", value: "logistics", group: "Business & Management" },
  {
    label: "Quality Management",
    value: "quality-management",
    group: "Business & Management",
  },
  {
    label: "Customer Service",
    value: "customer-service",
    group: "Business & Management",
  },
  {
    label: "Customer Success",
    value: "customer-success",
    group: "Business & Management",
  },
  {
    label: "Client Management",
    value: "client-management",
    group: "Business & Management",
  },
  { label: "Consulting", value: "consulting", group: "Business & Management" },
  {
    label: "Business Strategy",
    value: "business-strategy",
    group: "Business & Management",
  },
  {
    label: "Market Research",
    value: "market-research",
    group: "Business & Management",
  },
  {
    label: "Competitive Analysis",
    value: "competitive-analysis",
    group: "Business & Management",
  },

  // --- Marketing & Sales ---
  {
    label: "Digital Marketing",
    value: "digital-marketing",
    group: "Marketing & Sales",
  },
  {
    label: "Social Media Marketing",
    value: "social-media-marketing",
    group: "Marketing & Sales",
  },
  {
    label: "Content Marketing",
    value: "content-marketing",
    group: "Marketing & Sales",
  },
  {
    label: "SEO (Search Engine Optimization)",
    value: "seo",
    group: "Marketing & Sales",
  },
  {
    label: "SEM (Search Engine Marketing)",
    value: "sem",
    group: "Marketing & Sales",
  },
  {
    label: "Email Marketing",
    value: "email-marketing",
    group: "Marketing & Sales",
  },
  {
    label: "Affiliate Marketing",
    value: "affiliate-marketing",
    group: "Marketing & Sales",
  },
  {
    label: "Growth Hacking",
    value: "growth-hacking",
    group: "Marketing & Sales",
  },
  { label: "Branding", value: "branding", group: "Marketing & Sales" },
  {
    label: "Public Relations (PR)",
    value: "public-relations",
    group: "Marketing & Sales",
  },
  { label: "Advertising", value: "advertising", group: "Marketing & Sales" },
  { label: "Copywriting", value: "copywriting", group: "Marketing & Sales" },
  { label: "Sales", value: "sales", group: "Marketing & Sales" },
  {
    label: "Lead Generation",
    value: "lead-generation",
    group: "Marketing & Sales",
  },
  {
    label: "Sales Management",
    value: "sales-management",
    group: "Marketing & Sales",
  },
  {
    label: "Account Management",
    value: "account-management",
    group: "Marketing & Sales",
  },
  {
    label: "Business Development",
    value: "business-development",
    group: "Marketing & Sales",
  },
  {
    label: "Market Research",
    value: "market-research",
    group: "Marketing & Sales",
  },
  {
    label: "Customer Relationship Management (CRM)",
    value: "customer-relationship-management",
    group: "Marketing & Sales",
  },
  { label: "E-commerce", value: "e-commerce", group: "Marketing & Sales" },

  // --- Arts, Music & Entertainment ---
  { label: "Acting", value: "acting", group: "Arts, Music & Entertainment" },
  { label: "Singing", value: "singing", group: "Arts, Music & Entertainment" },
  { label: "Dancing", value: "dancing", group: "Arts, Music & Entertainment" },
  {
    label: "Music Performance",
    value: "music-performance",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Instrument Playing (e.g., Guitar, Piano)",
    value: "instrument-playing",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Music Composition",
    value: "music-composition",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Songwriting",
    value: "songwriting",
    group: "Arts, Music & Entertainment",
  },
  { label: "DJing", value: "djing", group: "Arts, Music & Entertainment" },
  {
    label: "Music Production",
    value: "music-production",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Sound Engineering",
    value: "sound-engineering",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Film/Video Production",
    value: "film-video-production",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Screenwriting",
    value: "screenwriting",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Directing",
    value: "directing",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Producing",
    value: "producing",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Stand-up Comedy",
    value: "stand-up-comedy",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Improvisation",
    value: "improvisation",
    group: "Arts, Music & Entertainment",
  },
  { label: "Theater", value: "theater", group: "Arts, Music & Entertainment" },
  {
    label: "Fine Arts",
    value: "fine-arts",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Sculpting",
    value: "sculpting",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Painting",
    value: "painting",
    group: "Arts, Music & Entertainment",
  },
  { label: "Drawing", value: "drawing", group: "Arts, Music & Entertainment" },
  {
    label: "Ceramics",
    value: "ceramics",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Photography",
    value: "photography",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Filmmaking",
    value: "filmmaking",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Vlogging",
    value: "vlogging",
    group: "Arts, Music & Entertainment",
  },
  {
    label: "Podcasting",
    value: "podcasting",
    group: "Arts, Music & Entertainment",
  },

  // --- Culinary Arts ---
  { label: "Cooking", value: "cooking", group: "Culinary Arts" },
  { label: "Baking", value: "baking", group: "Culinary Arts" },
  { label: "Pastry Arts", value: "pastry-arts", group: "Culinary Arts" },
  { label: "Culinary Arts", value: "culinary-arts", group: "Culinary Arts" },
  { label: "Bartending", value: "bartending", group: "Culinary Arts" },
  { label: "Mixology", value: "mixology", group: "Culinary Arts" },
  {
    label: "Wine Tasting/Sommelier",
    value: "wine-tasting-sommelier",
    group: "Culinary Arts",
  },
  { label: "Food Styling", value: "food-styling", group: "Culinary Arts" },
  {
    label: "Recipe Development",
    value: "recipe-development",
    group: "Culinary Arts",
  },

  // --- Health & Wellness ---
  { label: "Yoga", value: "yoga", group: "Health & Wellness" },
  { label: "Meditation", value: "meditation", group: "Health & Wellness" },
  { label: "Pilates", value: "pilates", group: "Health & Wellness" },
  {
    label: "Personal Training",
    value: "personal-training",
    group: "Health & Wellness",
  },
  { label: "Nutrition", value: "nutrition", group: "Health & Wellness" },
  { label: "Dietician", value: "dietician", group: "Health & Wellness" },
  {
    label: "Massage Therapy",
    value: "massage-therapy",
    group: "Health & Wellness",
  },
  { label: "Aromatherapy", value: "aromatherapy", group: "Health & Wellness" },
  { label: "Reflexology", value: "reflexology", group: "Health & Wellness" },
  { label: "Acupuncture", value: "acupuncture", group: "Health & Wellness" },

  // --- Sports & Fitness ---
  {
    label: "Fitness Training",
    value: "fitness-training",
    group: "Sports & Fitness",
  },
  { label: "Weightlifting", value: "weightlifting", group: "Sports & Fitness" },
  { label: "Running", value: "running", group: "Sports & Fitness" },
  { label: "Swimming", value: "swimming", group: "Sports & Fitness" },
  { label: "Cycling", value: "cycling", group: "Sports & Fitness" },
  {
    label: "Team Sports (e.g., Basketball, Soccer)",
    value: "team-sports",
    group: "Sports & Fitness",
  },
  {
    label: "Individual Sports (e.g., Tennis, Golf)",
    value: "individual-sports",
    group: "Sports & Fitness",
  },
  { label: "Martial Arts", value: "martial-arts", group: "Sports & Fitness" },
  { label: "Gymnastics", value: "gymnastics", group: "Sports & Fitness" },
  {
    label: "Dance (Ballet, Hip-Hop, etc.)",
    value: "dance",
    group: "Sports & Fitness",
  },
  { label: "Surfing", value: "surfing", group: "Sports & Fitness" },
  {
    label: "Skiing/Snowboarding",
    value: "skiing-snowboarding",
    group: "Sports & Fitness",
  },
  { label: "Rock Climbing", value: "rock-climbing", group: "Sports & Fitness" },

  // --- Crafts & Hobbies ---
  { label: "Knitting", value: "knitting", group: "Crafts & Hobbies" },
  { label: "Crocheting", value: "crocheting", group: "Crafts & Hobbies" },
  { label: "Sewing", value: "sewing", group: "Crafts & Hobbies" },
  { label: "Embroidery", value: "embroidery", group: "Crafts & Hobbies" },
  { label: "Quilting", value: "quilting", group: "Crafts & Hobbies" },
  { label: "Pottery", value: "pottery", group: "Crafts & Hobbies" },
  {
    label: "Jewelry Making",
    value: "jewelry-making",
    group: "Crafts & Hobbies",
  },
  { label: "Woodworking", value: "woodworking", group: "Crafts & Hobbies" },
  { label: "Metalworking", value: "metalworking", group: "Crafts & Hobbies" },
  { label: "Sculpting", value: "sculpting", group: "Crafts & Hobbies" },
  { label: "Calligraphy", value: "calligraphy", group: "Crafts & Hobbies" },
  { label: "Origami", value: "origami", group: "Crafts & Hobbies" },
  {
    label: "Model Building",
    value: "model-building",
    group: "Crafts & Hobbies",
  },
  { label: "Gardening", value: "gardening", group: "Crafts & Hobbies" },
  { label: "Floral Design", value: "floral-design", group: "Crafts & Hobbies" },

  // --- Languages ---
  { label: "English", value: "english", group: "Languages" },
  { label: "Spanish", value: "spanish", group: "Languages" },
  { label: "French", value: "french", group: "Languages" },
  { label: "German", value: "german", group: "Languages" },
  {
    label: "Chinese (Mandarin)",
    value: "chinese-mandarin",
    group: "Languages",
  },
  {
    label: "Chinese (Cantonese)",
    value: "chinese-cantonese",
    group: "Languages",
  },
  { label: "Japanese", value: "japanese", group: "Languages" },
  { label: "Korean", value: "korean", group: "Languages" },
  { label: "Arabic", value: "arabic", group: "Languages" },
  { label: "Russian", value: "russian", group: "Languages" },
  { label: "Portuguese", value: "portuguese", group: "Languages" },
  { label: "Italian", value: "italian", group: "Languages" },
  { label: "Hindi", value: "hindi", group: "Languages" },
  { label: "Bengali", value: "bengali", group: "Languages" },
  { label: "Swahili", value: "swahili", group: "Languages" },
  {
    label: "American Sign Language (ASL)",
    value: "american-sign-language",
    group: "Languages",
  },
  {
    label: "British Sign Language (BSL)",
    value: "british-sign-language",
    group: "Languages",
  },

  // --- Other ---
  {
    label: "Public Speaking",
    value: "public-speaking",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Presentation Skills",
    value: "presentation-skills",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Active Listening",
    value: "active-listening",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Nonverbal Communication",
    value: "nonverbal-communication",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Negotiation",
    value: "negotiation",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Persuasion",
    value: "persuasion",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Conflict Resolution",
    value: "conflict-resolution",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Mediation",
    value: "mediation",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Teamwork",
    value: "teamwork",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Collaboration",
    value: "collaboration",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Leadership",
    value: "leadership",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Mentoring",
    value: "mentoring",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Coaching",
    value: "coaching",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Emotional Intelligence",
    value: "emotional-intelligence",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Interpersonal Skills",
    value: "interpersonal-skills",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Networking",
    value: "networking",
    group: "Communication & Interpersonal Skills",
  },
  {
    label: "Time Management",
    value: "time-management",
    group: "Personal Development",
  },
  {
    label: "Organization",
    value: "organization",
    group: "Personal Development",
  },
  { label: "Planning", value: "planning", group: "Personal Development" },
  {
    label: "Prioritization",
    value: "prioritization",
    group: "Personal Development",
  },
  {
    label: "Problem-Solving",
    value: "problem-solving",
    group: "Personal Development",
  },
  {
    label: "Decision-Making",
    value: "decision-making",
    group: "Personal Development",
  },
  {
    label: "Critical Thinking",
    value: "critical-thinking",
    group: "Personal Development",
  },
  {
    label: "Analytical Skills",
    value: "analytical-skills",
    group: "Personal Development",
  },
  {
    label: "Adaptability",
    value: "adaptability",
    group: "Personal Development",
  },
  { label: "Resilience", value: "resilience", group: "Personal Development" },
  {
    label: "Stress Management",
    value: "stress-management",
    group: "Personal Development",
  },
  {
    label: "Self-Motivation",
    value: "self-motivation",
    group: "Personal Development",
  },
  {
    label: "Self-Confidence",
    value: "self-confidence",
    group: "Personal Development",
  },
  {
    label: "Personal Finance",
    value: "personal-finance",
    group: "Personal Development",
  },
  { label: "Investing", value: "investing", group: "Personal Development" },
  { label: "Budgeting", value: "budgeting", group: "Personal Development" },
  {
    label: "Travel Planning",
    value: "travel-planning",
    group: "Personal Development",
  },
  {
    label: "Event Planning",
    value: "event-planning",
    group: "Personal Development",
  },
  {
    label: "Volunteering",
    value: "volunteering",
    group: "Personal Development",
  },
  { label: "Fundraising", value: "fundraising", group: "Personal Development" },
  { label: "Teaching", value: "teaching", group: "Education & Training" },
  { label: "Tutoring", value: "tutoring", group: "Education & Training" },
  {
    label: "Curriculum Development",
    value: "curriculum-development",
    group: "Education & Training",
  },
  {
    label: "Instructional Design",
    value: "instructional-design",
    group: "Education & Training",
  },
  { label: "E-Learning", value: "e-learning", group: "Education & Training" },
  {
    label: "Academic Writing",
    value: "academic-writing",
    group: "Education & Training",
  },
  { label: "Research", value: "research", group: "Education & Training" },
  {
    label: "Scientific Method",
    value: "scientific-method",
    group: "Education & Training",
  },
]
