import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/components/button.tsx",
    "src/components/card.tsx",
    "src/components/input.tsx",
    "src/components/label.tsx",
    "src/components/dialog.tsx",
    "src/components/toast.tsx",
    "src/components/badge.tsx",
    "src/components/avatar.tsx",
    "src/components/accordion.tsx",
    "src/components/alert.tsx",
    "src/components/checkbox.tsx",
    "src/components/select.tsx",
    "src/components/switch.tsx",
    "src/components/textarea.tsx",
    "src/components/separator.tsx",
    "src/components/skeleton.tsx",
    "src/components/progress.tsx",
    "src/components/slider.tsx",
    "src/components/tabs.tsx",
    "src/components/table.tsx",
    "src/components/popover.tsx",
    "src/components/tooltip.tsx",
    "src/components/dropdown-menu.tsx",
    "src/components/navigation-menu.tsx",
    "src/components/breadcrumb.tsx",
    "src/components/calendar.tsx",
    "src/components/carousel.tsx",
    "src/components/command.tsx",
    "src/components/context-menu.tsx",
    "src/components/drawer.tsx",
    "src/components/hover-card.tsx",
    "src/components/input-otp.tsx",
    "src/components/menubar.tsx",
    "src/components/pagination.tsx",
    "src/components/radio-group.tsx",
    "src/components/resizable.tsx",
    "src/components/scroll-area.tsx",
    "src/components/sheet.tsx",
    "src/components/sidebar.tsx",
    "src/components/toggle.tsx",
    "src/components/toggle-group.tsx",
    "src/components/sonner.tsx",
    "src/components/aspect-ratio.tsx",
    "src/components/chart.tsx",
    "src/lib/utils.ts",
    "src/hooks/use-mobile.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
});
